# Thanks AAA3A-AAA3A for that (https://github.com/AAA3A-AAA3A/AAA3A-AAA3A/blob/main/.github/workflows/main.yml)!
name: Metrics
on:
  # Schedule updates (each hour).
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit.
  workflow_dispatch:
  push: {branches: ["main", "master"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: GitGinocchio
          #template: classic
          base: "" #header, activity, community, repositories, metadata
          config_timezone: Europe/Rome

          plugin_code: yes

          plugin_achievements: yes
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          plugin_achievements_display: compact
          plugin_achievements_limit: 6

          #plugin_activity: yes
          #plugin_activity_days: 14
          #plugin_activity_filter: public
          #plugin_activity_limit: 5
          #plugin_activity_load: 300
          #plugin_activity_visibility: public

          plugin_contributors: yes
          plugin_contributors_head: master
          plugin_contributors_ignored: github-actions[bot], dependabot[bot], dependabot-preview[bot]
          plugin_contributors_sections: contributors

          #plugin_gists: yes

          plugin_habits: yes
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_habits_charts_type: classic

          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          plugin_languages: yes
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%

          plugin_lines: yes

          #plugin_notable: yes

          #plugin_posts: yes
          #plugin_posts_limit: 4
          #plugin_posts_user: .user.login

          #plugin_projects: yes
          #plugin_projects_limit: 4

          #plugin_repositories: yes
          #plugin_repositories_affiliations: owner
          #plugin_repositories_pinned: 3
          #plugin_repositories_starred: 0
          #plugin_repositories_random: 1

          #plugin_stargazers: yes

          plugin_traffic: yes